name: Android CI

on:
  release:
    types: [ published ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean :app:assembleRelease --stacktrace
    - name: Send APK to Telegram
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: chmod +x ./send-telegram.sh && ./send-telegram.sh
    - uses: actions/upload-artifact@master
      with:
        name: Release APK
        path: app/build/outputs/apk/release
